package apps.energy_insight_dashboard.ui

import androidx.compose.ui.graphics.Color

val EnergyPrimaryBlue = Color(0XFF2396EF)
val PrimaryText = Color(0XFF1D1D1D)
val MenuHeaderText = Color(0XFF405D9F)
val MenuItemText = Color(0XFF6C7894)
val ViewAllText = Color(0XFF3C80F7)
val AddMemberText = Color(0XFF3F7DF8)
val TurnedOnDot = Color(0XFF2BEDB3)
val TurnedOffDot = Color(0XFFFF6E6E)
val SectionTitle = Color(0XFF2B2B2B)
val DevicesSectionIconBg = Color(0XFF3E7EF7)
val DevicesSectionText = Color(0XFF284680)
val DevicesSectionSelectedBg = Color(0XFFC3DBFF)
val DevicesSectionStatusText = Color(0XFF5C5C5C)
val SwitchTrackUnChecked = Color(0XFF929BA3)
val SwitchTrackChecked = Color(0XFF3E7EF7)
val LevelNameText = Color(0XFF505050)
val LevelHumidityIconBg = Color(0XFF2892F0)
val LevelEnergyIconBg = Color(0XFFB16CFF)
val DividerColor = Color(0XFFBCB5B5)
val DashboardSwitchTrackUnCheckedStart = Color(0XFFF71983)
val DashboardSwitchTrackUnCheckedEnd = Color(0XFFFF8D52)