package apps.currency_converter_udemy.domain.model

import org.jetbrains.compose.resources.DrawableResource

enum class CurrencyCode(
    val country: String,
    val flag: DrawableResource? = null
) {
    AED("United Arab Emirates"),
    AFN("Afghanistan"),
    ALL("Albania"),
    AMD("Armenia"),
    ANG("Netherlands Antilles"),
    AOA("Angola"),
    ARS("Argentina"),
    AUD("Australia"),
    AWG("Aruba"),
    AZN("Azerbaijan"),
    BAM("Bosnia and Herzegovina"),
    BBD("Barbados"),
    BDT("Bangladesh"),
    BGN("Bulgaria"),
    BHD("Bahrain"),
    BIF("Burundi"),
    BMD("Bermuda"),
    BND("Brunei"),
    BOB("Bolivia"),
    BRL("Brazil"),
    BSD("Bahamas"),
    BTN("Bhutan"),
    BWP("Botswana"),
    BYN("Belarus"),
    BYR("Belarus"), // Replaced by BYN in 2016
    BZD("Belize"),
    CAD("Canada"),
    CDF("Democratic Republic of the Congo"),
    CHF("Switzerland"),
    CLF("Chile"), // CLF is a unit of account in Chile
    CLP("Chile"),
    CNY("China"),
    COP("Colombia"),
    CRC("Costa Rica"),
    CUC("Cuba"),
    CUP("Cuba"),
    CVE("Cape Verde"),
    CZK("Czech Republic"),
    DJF("Djibouti"),
    DKK("Denmark"),
    DOP("Dominican Republic"),
    DZD("Algeria"),
    EGP("Egypt"),
    ERN("Eritrea"),
    ETB("Ethiopia"),
    EUR("European Union"),
    FJD("Fiji"),
    FKP("Falkland Islands"),
    GBP("United Kingdom"),
    GEL("Georgia"),
    GGP("Guernsey"),
    GHS("Ghana"),
    GIP("Gibraltar"),
    GMD("Gambia"),
    GNF("Guinea"),
    GTQ("Guatemala"),
    GYD("Guyana"),
    HKD("Hong Kong"),
    HNL("Honduras"),
    HRK("Croatia"),
    HTG("Haiti"),
    HUF("Hungary"),
    IDR("Indonesia"),
    ILS("Israel"),
    IMP("Isle of Man"),
    INR("India"),
    IQD("Iraq"),
    IRR("Iran"),
    ISK("Iceland"),
    JEP("Jersey"),
    JMD("Jamaica"),
    JOD("Jordan"),
    JPY("Japan"),
    KES("Kenya"),
    KGS("Kyrgyzstan"),
    KHR("Cambodia"),
    KMF("Comoros"),
    KPW("North Korea"),
    KRW("South Korea"),
    KWD("Kuwait"),
    KYD("Cayman Islands"),
    KZT("Kazakhstan"),
    LAK("Laos"),
    LBP("Lebanon"),
    LKR("Sri Lanka"),
    LRD("Liberia"),
    LSL("Lesotho"),
    LTL("Lithuania"),
    LVL("Latvia"),
    LYD("Libya"),
    MAD("Morocco"),
    MDL("Moldova"),
    MGA("Madagascar"),
    MKD("North Macedonia"),
    MMK("Myanmar"),
    MNT("Mongolia"),
    MOP("Macau"),
    MRO("Mauritania"), // Replaced by MRU in 2018
    MRU("Mauritania"),
    MUR("Mauritius"),
    MVR("Maldives"),
    MWK("Malawi"),
    MXN("Mexico"),
    MYR("Malaysia"),
    MZN("Mozambique"),
    NAD("Namibia"),
    NGN("Nigeria"),
    NIO("Nicaragua"),
    NOK("Norway"),
    NPR("Nepal"),
    NZD("New Zealand"),
    OMR("Oman"),
    PAB("Panama"),
    PEN("Peru"),
    PGK("Papua New Guinea"),
    PHP("Philippines"),
    PKR("Pakistan"),
    PLN("Poland"),
    PYG("Paraguay"),
    QAR("Qatar"),
    RON("Romania"),
    RSD("Serbia"),
    RUB("Russia"),
    RWF("Rwanda"),
    SAR("Saudi Arabia"),
    SBD("Solomon Islands"),
    SCR("Seychelles"),
    SDG("Sudan"),
    SEK("Sweden"),
    SGD("Singapore"),
    SHP("Saint Helena"),
    SLL("Sierra Leone"),
    SOS("Somalia"),
    SRD("Suriname"),
    STD("São Tomé and Príncipe"), // Replaced by STN in 2018
    STN("São Tomé and Príncipe"),
    SVC("El Salvador"),
    SYP("Syria"),
    SZL("Eswatini"),
    THB("Thailand"),
    TJS("Tajikistan"),
    TMT("Turkmenistan"),
    TND("Tunisia"),
    TOP("Tonga"),
    TRY("Turkey"),
    TTD("Trinidad and Tobago"),
    TWD("Taiwan"),
    TZS("Tanzania"),
    UAH("Ukraine"),
    UGX("Uganda"),
    USD("United States"),
    UYU("Uruguay"),
    UZS("Uzbekistan"),
    VEF("Venezuela"), // Replaced by VES
    VES("Venezuela"),
    VND("Vietnam"),
    VUV("Vanuatu"),
    WST("Samoa"),
    XAF("Central African CFA franc"),
    XCD("East Caribbean dollar"),
    XDR("International Monetary Fund (Special Drawing Rights)"),
    XOF("West African CFA franc"),
    XPF("CFP franc"),
    YER("Yemen"),
    ZAR("South Africa"),
    ZMK("Zambia"), // Replaced by ZMW in 2013
    ZMW("Zambia"),
    ZWL("Zimbabwe")
}
